mobxjs/zh.mobx.js.org

docs/api.md

同步文档 https://github.com/mobxjs/mobx/pull/2828

同步官方API.md更改

---

README.md
docs/LINKS.md
docs/README.md

更新贡献者&修复破损链接

---

docs/README.md

docs: update contributor and fix broken link

---

docs/mobx-utils.md

docs: mobx-utils.md

---

docs/README.md

docs: update official doc contributor

---

README.md

add new contributor YuFengDing

---

docs/react-optimizations.md

docs: react-optimizations.md

---

docs/custom-observables.md

docs: custom-observables.md

---

docs/observable-state.md

docs: observable-state.md

---

docs/README.md

doc: add translator to home page

---

docs/README.md

fix the translator github profile link

---

docs/README.md

chore: updated DCSL sponsor details

---

website/i18n/en.json
website/siteConfig.js

Add google analytics for zh.mobx.js.org

website: change the siteConfig and update google ga

---

docs/collection-utilities.md

docs: collection-utilities.md

---

docs/README.md

doc: add standout-jjc github avatar to homepage

---

README.md

add new contributor Rain120

---

docs/README.md

add wuxyman to homepage as contributor

---

docs/computeds.md

docs: computeds.md

---

docs/react-integration.md

New branch for resolve merge conflict, origin branch author @Cyberhan123

docs: react-integration.md

---

README.md

Thanks for your contribution. @chenxiaochun

add new contributor chenxiaochun to repo's readme

---

docs/lazy-observables.md

docs: lazy-observables.md

---

README.md
docs/README.md

Thanks for your translation work @newraina

add new contributor newraina

---

README.md
docs/configuration.md

docs: configuration.md

---

docs/README.md

Add YuFengDing to mobx doc homepage

---

docs/installation.md

- 安装方式
- 类属性的转换
- Proxy支持不好的引擎中的降级方案
- Mobx6 不建议使用装饰器，但是支持使用装饰器

docs: installation.md

---

docs/README.md

Add TheFirstSunday to mobx doc homepage

---

docs/observable-state.md

Observable state page use english word

---

README.md

Add vercel deploy status badge

---

docs/reactions.md

docs: reactions.md

---

docs/react-optimizations.md

sync with upstream https://github.com/mobxjs/mobx/pull/3031

Sync with upstream#3031 change

---

docs/react-integration.md

尽可能（晚）让Mobx获得值；被原标题误导，看了英文版才豁然开朗

Update react-integration.md 

---

README.md

chore: change readme.md

---

docs/actions.md
docs/observable-state.md

[done](https://github.com/mobxjs/zh.mobx.js.org/issues/76#issue-870574180)

chore: sync with change (actions and observable-state) #76

---

README.md

Add new contributor JevonsCode

---

README.md

Add new contributor finalwhy

---

docs/understanding-reactivity.md

前段时间在忙其他的东西，现在重新认领，明天就翻译完，是我怠慢了。

docs: understanding-reactivity.md

---

docs/README.md

Add cufoon to official doc homepage

---

README.md

doc(fix): fix contributor name

---

docs/backers-sponsors.md

翻译：https://zh.mobx.js.org/backers-sponsors.html

docs: backers-sponsors.md

---

README.md
docs/README.md

Same with title, @PiersZhang Thanks for contribution

Add piers zhang

---

README.md
docs/README.md

chore: add rain120 to README.md and homepage

---

README.md

[skip ci] chore: add new contributor zouHuaLu

---

docs/the-gist-of-mobx.md

chore: correct a misspelling of "derivations"

---

README.md

@ThornWu Thanks for your contribution

chore: add new contributor ThornWu

---

docs/README.md

修复错误 myTimer.create-> myTimer.increase

docs: update readme.md

---

README.md

chore: add new contributor moozeeli

---

README.md

chore: add new contirbutor  SageKwun

---

website/core/Footer.js
website/static/getting-started.html

https://support.google.com/analytics/answer/11583528 and 
https://support.google.com/analytics/answer/10759417
Make the switch to Google Analytics 4

chore: migrate to google analytics v4

---

docs/subclassing.md

override haven't imported

---

docs/understanding-reactivity.md

message.updateMessage --> message.updateTitle

message.updateMessage undifined

---

docs/the-gist-of-mobx.md

docs: fix statement and punctuation errors

---

README.md

cc @Tsuizen @iDestin Thank you, guys.

chore: add new contributer Tsuizen and iDestin

---

docs/enabling-decorators.md

chore: update enabling-decorators.md

---

docs/configuration.md

chrore: update configuration.md

---

README.md

chore: add new contributor JiangJie

---

README.md

新增贡献者 @TechQuery , 去掉过时的翻译激励信息

chore: add @TechQuery and remove translation bonus info
